ASPNetMVCAppInterboden/Controllers/WohnungenController.cs
using ASPNetMVCAppInterboden.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNetMVCAppInterboden.Controllers
{
    public class WohnungenController : Controller
    {
        private WohnungenContext context;
        public WohnungenController(WohnungenContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var model = context.Wohnungen.Where(w => w.IstInaktiv == false); ;
            return View(model);
        }

        public IActionResult Neu()
        {
            return View(new Wohnung());
        }

        public async Task<IActionResult> ErstellenOderBearbeiten(int? id)
        {
            if (id == null || id == 0)
            {
                return View(new Wohnung());
            }
            else
            {
                var wohnung = await context.Wohnungen.FindAsync(id);
                if (wohnung == null)
                {
                    return NotFound();
                }
                return View(wohnung);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ErstellenOderBearbeiten(int? id, [Bind("Id,Beschreibung,Strasse,Postleitzahl,Ort,IstInaktiv")] Wohnung wohnung)
        {
            if (ModelState.IsValid)
            {
                if (id == null || id == 0)
                {
                    context.Wohnungen.Add(wohnung);
                    await context.SaveChangesAsync();
                }
                else
                {
                    try
                    {
                        context.Wohnungen.Update(wohnung);
                        await context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!context.Wohnungen.Any(w => w.Id == wohnung.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                // Um im JQuery Script zu unterscheiden, ob die Anfrage gültig ist, Json-Objekt erstellen, mit Gültigkeit und View als Html-String
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_WohnungsUebersicht", context.Wohnungen.Where(w => w.IstInaktiv == false)) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "ErstellenOderBearbeiten", wohnung) });
        }

    }
}

ASPNetMVCAppInterboden/Views/Shared/_Layout.cshtml
<DOCTYPE html>

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>
            @ViewData["Title"] - Interboden
        </title>

        <link rel="stylesheet" href="~/lib/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-dark bg-dark">
                <a class="nav-link text-white" asp-controller="Wohnungen" asp-action="Index">Wohnungen</a>
            </nav>
        </header>
        <div class="container">
            <h1>@ViewData["Title"]</h1>
            <br />
            @RenderBody()
        </div>

        <footer></footer>

        <script src="~/lib/js/jquery-3.4.0.min.js"></script>
        <script src="~/lib/js/bootstrap.bundle.min.js"></script>
        @RenderSection("Scripts", required: false)
        <script src="~/js/site.js"></script>
    </body>
</html>

ASPNetMVCAppInterboden/Views/Wohnungen/ErstellenOderBearbeiten.cshtml
@model ASPNetMVCAppInterboden.Model.Wohnung
@{
    Layout = null;
}

<form asp-action="ErstellenOderBearbeiten" asp-route-id="@Model.Id" onsubmit="return saveForm(this)">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Beschreibung" class="control-label">@Html.DisplayNameFor(model => model.Beschreibung)</label>
        <input asp-for="Beschreibung" class="form-control" />
        <span asp-validation-for="Beschreibung" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Strasse" class="control-label">@Html.DisplayNameFor(model => model.Strasse)</label>
        <input asp-for="Strasse" class="form-control" />
        <span asp-validation-for="Strasse" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Postleitzahl" class="control-label">@Html.DisplayNameFor(model => model.Postleitzahl)</label>
                <input asp-for="Postleitzahl" class="form-control" />
                <span asp-validation-for="Postleitzahl" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <label asp-for="Ort" class="control-label">@Html.DisplayNameFor(model => model.Ort)</label>
                <input asp-for="Ort" class="form-control" />
                <span asp-validation-for="Ort" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" asp-for="IstInaktiv" />
        <label class="form-check-label">
            @Html.DisplayNameFor(model => model.IstInaktiv)
        </label>
    </div>
    <input type="submit" value="Speichern" class="btn btn-primary btn-block" />
    <button type="button" class="btn btn-outline-primary btn-block" data-dismiss="modal">Schließen</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASPNetMVCAppInterboden/Views/Wohnungen/Index.cshtml
@model IEnumerable<ASPNetMVCAppInterboden.Model.Wohnung>

@{
    ViewData["Title"] = "Wohnungsübersicht";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div id="content" class="col-sm-12">
        @await Html.PartialAsync("_WohnungsUebersicht", Model)
    </div>

    <div class="modal fade" id="popup">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>x</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

</div>

ASPNetMVCAppInterboden/Views/Wohnungen/_NeuesteWohnung.cshtml
@model ASPNetMVCAppInterboden.Model.Wohnung
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="col-sm-6">
    @if (Model != null)
    {
        <div class="card ">
            <div class="card-header">Neueste Wohnung</div>
            <div class="card-body">
                <h5 class="card-title">@Model.Beschreibung</h5>
            </div>
        </div>
    }

</div>

ASPNetMVCAppInterboden/Views/Wohnungen/_WohnungsUebersicht.cshtml
@model IEnumerable<ASPNetMVCAppInterboden.Model.Wohnung>
@{ 
    var neuesteWohnung = Model.LastOrDefault();
}

@if(neuesteWohnung != null)
{
    await Html.RenderPartialAsync("_NeuesteWohnung", neuesteWohnung);
}
<br />
<div class="col-sm-12">
    <div class="table-responsive">
        <table class="table">
            <tr>
            </tr>
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Beschreibung)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Strasse)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Postleitzahl)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Ort)
                    </th>
                    <th>
                        <button type="button" onclick="openPopup('@Url.Action("ErstellenOderBearbeiten", "Wohnungen", new { id = 0 })', 'Neue Wohnung')" class="btn btn-success btn-block">
                            <i class="fas fa-plus"></i>  Neue Wohnung
                        </button>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var wohnung in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => wohnung.Beschreibung)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => wohnung.Strasse)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => wohnung.Postleitzahl)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => wohnung.Ort)
                        </td>
                        <td>
                            <button type="button" onclick="openPopup('@Url.Action("ErstellenOderBearbeiten", "Wohnungen", new { id = wohnung.Id })', 'Wohnung bearbeiten')" class="btn btn-outline-primary btn-block">
                                <i class="far fa-edit"></i> Bearbeiten
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" class="table-secondary text-right">Aktive Wohnungen: @Model.Count()</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>